FROM php:8.2-cli

# Install extension
RUN apt-get update && apt-get install -y \
    unzip git curl libicu-dev libonig-dev \
    && docker-php-ext-install intl mbstring pdo pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy source
WORKDIR /app
COPY . .

# Install dependencies
RUN composer install --no-dev --optimize-autoloader

# Jalankan spark serve
CMD ["sh", "-c", "php spark serve --host=0.0.0.0 --port=${PORT:-8080}"]
